#pragma config(Sensor, S2,     corE,           sensorEV3_Color)
#pragma config(Sensor, S3,     corD,           sensorEV3_Color)
#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "EV3Arduino.h"

int distF, distD, distE;
int rD, gD, bD;
int rE, gE, bE;

task sensors()
{
	while(1){
		distF = readArduino(S1, 0);
		distD = readArduino(S1, 1);
		distE = readArduino(S1, 2);
		getColorRGB(corD, rD, gD, bD);
		getColorRGB(corE, rE, gE, bE);
	}
}

task main()
{

	startTask(sensors);
	while(1){
		displayTextLine(1, "%d", distF);
		if(distF<=8)
		{
			playSound(soundBeepBeep);
			sleep(500);
		}
		clearSounds();

	}

}
